imjp19
clubgamma/Awesome-Web-Art pull request #30
Opened 2020-10-02 07:07 UTC by imjp19

- [X] I have read the Code Of Conduct.
- [X] I have followed all the steps of submission properly.

2020-10-02 13:31 UTC, imjp19 commented
Now please check once.

2020-10-02 13:50 UTC, jayskhatri commented
Thanks @imjp19 , for opening the pull request! 👏

I'll be reviewing your pull request thoroughly

Star ⭐ this project and [tweet](https://twitter.com/share?text=Contributed+to+awesome+projects+at+@club_gamma&url=https://clubgamma.github.io/hacktoberfest) about your contributions and also you can join the [discord channel of club gamma](https://discord.gg/kjnp6wU)

2020-10-02 13:52 UTC, jayskhatri requested changes
Please do necessary changes then after PR is ready to be merged

Happy hacking🚀

2020-10-02 13:52 UTC, jayskhatri commented on README.md
> +| <img src="https://github.com/imjp19/Awesome-Web-Art/blob/master/imjp19/HOVER.gif" width=80% height=70%> | [Find the code here](https://github.com/imjp19/Awesome-Web-Art/blob/master/imjp19/button-ho
Hey @imjp19 what you have added is not in proper aligned table, [check here](https://github.com/clubgamma/Awesome-Web-Art/blob/021a370bcb4fc894b174919031c25f9a8f4b606a/README.md) in the last 2 rows the table is broke.

2020-10-03 03:57 UTC, jayskhatri approved these changes
Good to go👍

2020-10-03 03:57 UTC, merged

2020-11-04 05:17 UTC, yashpaneliya commented
Hello contributor👋,

As we all know that Hacktoberfest-2020 is ended. Hope you enjoyed it a lot and made some awesome contributions. 
So now it's time for schwags🎁🤩

**Send your email (linked with your GitHub account) in the reply of this comment. Mention any one of the maintainers (@yashpaneliya @rudrabarad @harshptl14 @chirayu-joshi @dhruvpatel1706 ) in the reply.**

**We'll send a form on the email you'll provide. Please reply ASAP.**

Join [Club Gamma Discord](https://discord.com/invite/kjnp6wU) for future updates.

2020-11-04 05:20 UTC, imjp19 commented
jaypatel19124@gmail.com @yashpaneliya